apiVersion: v2
appVersion: "1.0"
description: A Helm chart for civil-sdt-commissioning App
name: civil-sdt-commissioning
home: https://github.com/hmcts/civil-sdt-commissioning
version: 0.1.10
maintainers:
  - name: HMCTS sdt team
dependencies:
  - name: java
    version: 5.2.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
